apiVersion: v1
kind: Pod
metadata:
  name: sidecar
spec:
  volumes:
  - name: shared-logs 
    emptyDir: {}
  containers:
  - name: main-container
    image: alpine 
    command: ["/bin/sh"]
    args: ["-c", "ping google.com >> /tmp/index.html; sleep 60;done"]
    volumeMounts:
    - name: shared-logs
      mountPath: /tmp
  - name: sidecar-container
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /usr/share/nginx/html
